# class HeaderKey:

INTEGRATION_GROUP_ID_HEADER_KEY = "X-INTEGRATION_GROUP_ID"

COLLECTOR_ID_HEADER_KEY = "X-COLLECTOR-ID"

PROFILER_ID_HEADER_KEY = "X-PROFILER-ID"

INTEGRATION_ID_HEADER_KEY = "X-INTEGRATION-ID"

COMPANY_USER_HEADER_KEY = "X-COMPANY_USER"

SENSOR_ID_HEADER_KEY = "X-SENSOR-ID"

PRODUCT_ID_HEADER_KEY = "X-PRODUCT-ID"

PRODUCT_HEADER_KEY = "X-PRODUCT-KEY"

DEBUGGER_TYPE_HEADER_KEY = "X-DEBUGGER-TYPE"

SERVICE_NAME_HEADER_KEY = "X-SERVICE-NAME"

PRODUCT_NAME_HEADER_KEY = "X-PRODUCT-NAME"

API_KEY_HEADER_KEY = "X-API-KEY"

AUTHORIZATION_HEADER_KEY = "Authorization"

AUTHORIZATION_BEARER_KEY = "Bearer"

CSRF_TOKEN_HEADER_KEY = "X-CSRF-TOKEN"

REQUEST_ID_HEADER_KEY = "X-Request-ID"

VERIFY_ACTIVE_SESSION_KEY_HEADER_KEY = "X-VERIFY-ACTIVE-SESSION"
VERIFY_SESSION_TOKEN_HEADER_KEY = "X-VERIFY-SESSION-TOKEN"
VERIFY_ACCESS_TOKEN_HEADER_KEY = "X-VERIFY-ACCESS-TOKEN"
VERIFY_REFRESH_TOKEN_HEADER_KEY = "X-VERIFY-REFRESH-TOKEN"

RESPONSE_TIME_HEADER_KEY = "X-Response-Time"


FORWARDED_PROTO_HEADER_KEY = "x-forwarded-proto"
FORWARDED_FOR_HEADER_KEY = "x-forwarded-for"

FORWARD_PROTO_HEADER_KEY = "x-forward-proto"
FORWARD_FOR_HEADER_KEY = "x-forward-for"


CONTENT_TYPE_HEADER_KEY = "Content-Type"

ACCEPT_HEADER_KEY = "Accept"

USER_AGENT_HEADER_KEY = "User-Agent"
HOST_HEADER_KEY = "Host"
CACHE_CONTROL_HEADER_KEY = "Cache-Control"
ACCEPT_ENCODING_HEADER_KEY = "Accept-Encoding"
ACCEPT_LANGUAGE_HEADER_KEY = "Accept-Language"
CONNECTION_HEADER_KEY = "Connection"
CONTENT_LENGTH_HEADER_KEY = "Content-Length"
REFERER_HEADER_KEY = "Referer"
ORIGIN_HEADER_KEY = "Origin"
COOKIE_HEADER_KEY = "Cookie"


REQUESTED_WITH_HEADER_KEY = "X-Requested-With"
DNT_HEADER_KEY = "DNT"  # Do Not Track
FORWARDED_FOR_HEADER_KEY = "X-Forwarded-For"
FORWARDED_PROTO_HEADER_KEY = "X-Forwarded-Proto"
FRAME_OPTIONS_HEADER_KEY = "X-Frame-Options"
CONTENT_SECURITY_POLICY_HEADER_KEY = "Content-Security-Policy"
STRICT_TRANSPORT_SECURITY_HEADER_KEY = "Strict-Transport-Security"
EXPECT_HEADER_KEY = "Expect"
IF_MATCH_HEADER_KEY = "If-Match"
IF_NONE_MATCH_HEADER_KEY = "If-None-Match"
IF_MODIFIED_SINCE_HEADER_KEY = "If-Modified-Since"
IF_UNMODIFIED_SINCE_HEADER_KEY = "If-Unmodified-Since"
UPGRADE_INSECURE_REQUESTS_HEADER_KEY = "Upgrade-Insecure-Requests"
ACCESS_CONTROL_ALLOW_ORIGIN_HEADER_KEY = "Access-Control-Allow-Origin"
ACCESS_CONTROL_ALLOW_METHODS_HEADER_KEY = "Access-Control-Allow-Methods"
ACCESS_CONTROL_ALLOW_HEADERS_HEADER_KEY = "Access-Control-Allow-Headers"
ACCESS_CONTROL_EXPOSE_HEADERS_HEADER_KEY = "Access-Control-Expose-Headers"
ACCESS_CONTROL_MAX_AGE_HEADER_KEY = "Access-Control-Max-Age"
TRANSFER_ENCODING_HEADER_KEY = "TE"  # Transfer Encoding
TRANSFER_ENCODING_HEADER_KEY = "Transfer-Encoding"  # Transfer Encoding
VIA_HEADER_KEY = "Via"
WARNING_HEADER_KEY = "Warning"
PRAGMA_HEADER_KEY = "Pragma"
ALPN_HEADER_KEY = "ALPN"  # Application-Layer Protocol Negotiation (ALPN)


SESSION_ID_HEADER_KEY = "X-Session-ID"
SESSION_TOKEN_HEADER_KEY = "X-Session-Token"
REFRESH_TOKEN_HEADER_KEY = "X-Refresh-Token"
ACCESS_TOKEN_HEADER_KEY = "X-Access-Token"
USER_ID_HEADER_KEY = "X-User-ID"
USER_EMAIL_HEADER_KEY = "X-User-Email"
USER_USERNAME_HEADER_KEY = "X-User-Username"
USER_IDENTIFIER_HEADER_KEY = "X-User-Identifier"
X_AUTH_TOKEN_HEADER_KEY = "X-Auth-Token"


CORRELATION_ID_HEADER_KEY = "X-Correlation-ID"
TRACE_ID_HEADER_KEY = "X-Trace-ID"
DEBUG_HEADER_KEY = "X-Debug"
LOG_LEVEL_HEADER_KEY = "X-Log-Level"

RESOURCE_ID_HEADER_KEY = "X-Resource-ID"


FEATURE_FLAG_HEADER_KEY = "X-Feature-Flag"
EXPERIMENT_ID_HEADER_KEY = "X-Experiment-ID"

XSS_PROTECTION_HEADER_KEY = "X-XSS-Protection"

X_CLIENT_ID_HEADER_KEY = "X-Client-ID"
X_ENVIRONMENT_HEADER_KEY = "X-Environment"
X_PLATFORM_HEADER_KEY = "X-Platform"
X_APP_VERSION_HEADER_KEY = "X-App-Version"
PERMISSIONS_POLICY_HEADER_KEY = "Permissions-Policy"


TENANT_ID_HEADER_KEY = "X-Tenant-ID"
REGION_HEADER_KEY = "X-Region"
TRANSACTION_ID_HEADER_KEY = "X-Transaction-ID"
WORKFLOW_ID_HEADER_KEY = "X-Workflow-ID"
PRIORITY_HEADER_KEY = "X-Priority"


RATE_LIMIT_HEADER_KEY = "X-Rate-Limit"
RETRY_AFTER_HEADER_KEY = "X-Retry-After"


ENCRYPTION_KEY_HEADER_KEY = "X-Encryption-Key"
SECURITY_TOKEN_HEADER_KEY = "X-Security-Token"


CUSTOMER_ID_HEADER_KEY = "X-Customer-ID"
DEPLOYMENT_VERSION_HEADER_KEY = "X-Deployment-Version"


ACCEPT_CHARSET_HEADER_KEY = "Accept-Charset"


SERVER_HEADER_KEY = "Server"  # Server software identification
SET_COOKIE_HEADER_KEY = "Set-Cookie"  # Set cookies in the client
VARY_HEADER_KEY = "Vary"  # Headers that affect caching


LOCATION_HEADER_KEY = "Location"  # URL for redirection
REFRESH_HEADER_KEY = "Refresh"  # Refresh the page after specified time


CONTENT_TYPE_OPTIONS_HEADER_KEY = (  # MIME sniffing protection
    "X-Content-Type-Options"
)


EXPIRES_HEADER_KEY = "Expires"
LAST_MODIFIED_HEADER_KEY = "Last-Modified"
ETAG_HEADER_KEY = "ETag"


ALLOW_HEADER_KEY = "Allow"
CONTENT_ENCODING_HEADER_KEY = (  # Encoding of the response body
    "Content-Encoding"
)
CONTENT_LANGUAGE_HEADER_KEY = (  # Language of the response body
    "Content-Language"
)
CONTENT_LOCATION_HEADER_KEY = (  # Alternate location for the returned content
    "Content-Location"
)
CONTENT_MD5_HEADER_KEY = (  # Base64-encoded MD5 checksum of the response body
    "Content-MD5"
)


# class HeaderKey:

INTEGRATION_GROUP_ID_HEADER_KEY = "X-INTEGRATION_GROUP_ID"

COLLECTOR_ID_HEADER_KEY = "X-COLLECTOR-ID"

PROFILER_ID_HEADER_KEY = "X-PROFILER-ID"

INTEGRATION_ID_HEADER_KEY = "X-INTEGRATION-ID"

COMPANY_USER_HEADER_KEY = "X-COMPANY_USER"

SENSOR_ID_HEADER_KEY = "X-SENSOR-ID"

PRODUCT_ID_HEADER_KEY = "X-PRODUCT-ID"

PRODUCT_HEADER_KEY = "X-PRODUCT-KEY"

DEBUGGER_TYPE_HEADER_KEY = "X-DEBUGGER-TYPE"

SERVICE_NAME_HEADER_KEY = "X-SERVICE-NAME"

PRODUCT_NAME_HEADER_KEY = "X-PRODUCT-NAME"

API_KEY_HEADER_KEY = "X-API-KEY"

AUTHORIZATION_HEADER_KEY = "Authorization"

AUTHORIZATION_BEARER_KEY = "Bearer"

CSRF_TOKEN_HEADER_KEY = "X-CSRF-TOKEN"

REQUEST_ID_HEADER_KEY = "X-Request-ID"

VERIFY_ACTIVE_SESSION_KEY_HEADER_KEY = "X-VERIFY-ACTIVE-SESSION"
VERIFY_SESSION_ID_TOKEN_KEY_HEADER_KEY = "X-VERIFY-ACTIVE-SESSION"
VERIFY_SESSION_TOKEN_HEADER_KEY = "X-VERIFY-SESSION-TOKEN"
VERIFY_ACCESS_TOKEN_HEADER_KEY = "X-VERIFY-ACCESS-TOKEN"
VERIFY_REFRESH_TOKEN_HEADER_KEY = "X-VERIFY-REFRESH-TOKEN"
VERIFY_CSRF_TOKEN_HEADER_KEY = "X-VERIFY-CSRF-TOKEN"
RESPONSE_TIME_HEADER_KEY = "X-Response-Time"


FORWARDED_PROTO_HEADER_KEY = "x-forwarded-proto"
FORWARDED_FOR_HEADER_KEY = "x-forwarded-for"

FORWARD_PROTO_HEADER_KEY = "x-forward-proto"
FORWARD_FOR_HEADER_KEY = "x-forward-for"


CONTENT_TYPE_HEADER_KEY = "Content-Type"

ACCEPT_HEADER_KEY = "Accept"

USER_AGENT_HEADER_KEY = "User-Agent"
HOST_HEADER_KEY = "Host"
CACHE_CONTROL_HEADER_KEY = "Cache-Control"
ACCEPT_ENCODING_HEADER_KEY = "Accept-Encoding"
ACCEPT_LANGUAGE_HEADER_KEY = "Accept-Language"
CONNECTION_HEADER_KEY = "Connection"
CONTENT_LENGTH_HEADER_KEY = "Content-Length"
REFERER_HEADER_KEY = "Referer"
ORIGIN_HEADER_KEY = "Origin"
COOKIE_HEADER_KEY = "Cookie"


REQUESTED_WITH_HEADER_KEY = "X-Requested-With"
DNT_HEADER_KEY = "DNT"  # Do Not Track
FORWARDED_FOR_HEADER_KEY = "X-Forwarded-For"
FORWARDED_PROTO_HEADER_KEY = "X-Forwarded-Proto"
FRAME_OPTIONS_HEADER_KEY = "X-Frame-Options"
CONTENT_SECURITY_POLICY_HEADER_KEY = "Content-Security-Policy"
STRICT_TRANSPORT_SECURITY_HEADER_KEY = "Strict-Transport-Security"
EXPECT_CT_HEADER_KEY = "Expect-CT"

EXPECT_HEADER_KEY = "Expect"
IF_MATCH_HEADER_KEY = "If-Match"
IF_NONE_MATCH_HEADER_KEY = "If-None-Match"
IF_MODIFIED_SINCE_HEADER_KEY = "If-Modified-Since"
IF_UNMODIFIED_SINCE_HEADER_KEY = "If-Unmodified-Since"
UPGRADE_INSECURE_REQUESTS_HEADER_KEY = "Upgrade-Insecure-Requests"
ACCESS_CONTROL_ALLOW_ORIGIN_HEADER_KEY = "Access-Control-Allow-Origin"
ACCESS_CONTROL_ALLOW_METHODS_HEADER_KEY = "Access-Control-Allow-Methods"
ACCESS_CONTROL_ALLOW_HEADERS_HEADER_KEY = "Access-Control-Allow-Headers"
ACCESS_CONTROL_EXPOSE_HEADERS_HEADER_KEY = "Access-Control-Expose-Headers"
ACCESS_CONTROL_MAX_AGE_HEADER_KEY = "Access-Control-Max-Age"
VIA_HEADER_KEY = "Via"
WARNING_HEADER_KEY = "Warning"
PRAGMA_HEADER_KEY = "Pragma"
ALPN_HEADER_KEY = "ALPN"  # Application-Layer Protocol Negotiation (ALPN)


SESSION_ID_HEADER_KEY = "X-Session-ID"
SESSION_TOKEN_HEADER_KEY = "X-Session-Token"
REFRESH_TOKEN_HEADER_KEY = "X-Refresh-Token"
ACCESS_TOKEN_HEADER_KEY = "X-Access-Token"
USER_ID_HEADER_KEY = "X-User-ID"
USER_EMAIL_HEADER_KEY = "X-User-Email"
USER_USERNAME_HEADER_KEY = "X-User-Username"
USER_IDENTIFIER_HEADER_KEY = "X-User-Identifier"
X_AUTH_TOKEN_HEADER_KEY = "X-Auth-Token"
SERVICE_ID_HEADER_KEY = "x-service-id"
DATE_HEADER_KEY = "date"

CORRELATION_ID_HEADER_KEY = "X-Correlation-ID"
TRACE_ID_HEADER_KEY = "X-Trace-ID"
DEBUG_HEADER_KEY = "X-Debug"
LOG_LEVEL_HEADER_KEY = "X-Log-Level"

RESOURCE_ID_HEADER_KEY = "X-Resource-ID"


FEATURE_FLAG_HEADER_KEY = "X-Feature-Flag"
EXPERIMENT_ID_HEADER_KEY = "X-Experiment-ID"


X_CLIENT_ID_HEADER_KEY = "X-Client-ID"
X_ENVIRONMENT_HEADER_KEY = "X-Environment"
X_PLATFORM_HEADER_KEY = "X-Platform"
X_APP_VERSION_HEADER_KEY = "X-App-Version"


TENANT_ID_HEADER_KEY = "X-Tenant-ID"
REGION_HEADER_KEY = "X-Region"
TRANSACTION_ID_HEADER_KEY = "X-Transaction-ID"
WORKFLOW_ID_HEADER_KEY = "X-Workflow-ID"
PRIORITY_HEADER_KEY = "X-Priority"


RATE_LIMIT_HEADER_KEY = "X-Rate-Limit"
RETRY_AFTER_HEADER_KEY = "X-Retry-After"


ENCRYPTION_KEY_HEADER_KEY = "X-Encryption-Key"
SECURITY_TOKEN_HEADER_KEY = "X-Security-Token"


CUSTOMER_ID_HEADER_KEY = "X-Customer-ID"
DEPLOYMENT_VERSION_HEADER_KEY = "X-Deployment-Version"


ACCEPT_CHARSET_HEADER_KEY = "Accept-Charset"


SERVER_HEADER_KEY = "Server"  # Server software identification
SET_COOKIE_HEADER_KEY = "Set-Cookie"  # Set cookies in the client
VARY_HEADER_KEY = "Vary"  # Headers that affect caching


LOCATION_HEADER_KEY = "Location"  # URL for redirection
REFRESH_HEADER_KEY = "Refresh"  # Refresh the page after specified time


CONTENT_TYPE_OPTIONS_HEADER_KEY = (  # MIME sniffing protection
    "X-Content-Type-Options"
)


EXPIRES_HEADER_KEY = "Expires"
LAST_MODIFIED_HEADER_KEY = "Last-Modified"
ETAG_HEADER_KEY = "ETag"


ALLOW_HEADER_KEY = "Allow"
CONTENT_ENCODING_HEADER_KEY = (  # Encoding of the response body
    "Content-Encoding"
)
CONTENT_LANGUAGE_HEADER_KEY = (  # Language of the response body
    "Content-Language"
)
CONTENT_LOCATION_HEADER_KEY = (  # Alternate location for the returned content
    "Content-Location"
)
CONTENT_MD5_HEADER_KEY = (  # Base64-encoded MD5 checksum of the response body
    "Content-MD5"
)


MOCK_HEADER_KEY = "X-Mock"
