ACCESS_TOKEN = "accessToken"
REFRESH_TOKEN = "refreshToken"
ID_TOKEN = "idToken"
USER_ID_TOKEN = "userIdToken"
USER_TOKEN = "userToken"
SESSION_TOKEN = "sessionToken"
SESSION_ID_TOKEN = "sessionIdToken"
CSRF_TOKEN = "csrfToken"
